### ISSUE TITLE
[MPR/electron-mail] Proposal to restructure and/or rename

### ISSUE THREAD

**Issue by ghost** [taivlam/aur-mpr-packages#1]
continuation from here:
https://github.com/vladimiry/ElectronMail/issues/684

1. lol... i actually never used it.
2. Don't worry about that, it happens some times. About the comment notifications, i'm not 100% sure, but i think that's broken for a while now.
3. Yea ok.
4. Upstream is the developer, vladimiry, here. He already builds debs and also publish their sha256, that's why it's preferable to use sha256. The AUR package actually builds a arch package. The mpr package, just unpacks and then repacks the deb that vladimiry makes... It's not completely useless, It's more convinient then downloading the deb your self manually. One of the changes that i made, is that the PKGBUILD just downloads the package and doesn't unpacks and then repacks it.
5. here i am
6. an email address would be preferable. Use a dedicated one for this.

The new PKGBUILD

[PKGBUILD.txt](https://github.com/taivlam/aur-mpr-packages/files/15150363/PKGBUILD.txt)

**Comment by taivlam** [comment]
* For the `v5.2.2` release [page](https://github.com/vladimiry/ElectronMail/releases/tag/v5.2.2), I see the SHA256 sums listed within the description.  (Some other projects will list the SHA256 sums as a clearly named `.txt` file.)
    * I'm starting to notice that more projects than I initially believed, as some might save checksums in YAML files that don't have `*sum* in their names`.
* There was some MPR downtime when I last wrote.  (Actually, the `makedeb` server was also down while the lead developer was moving about 1-2 days ago.)
* I'll set up a custom SL alias for my MPR & AUR packages.

I'll start making corresponding changes for any other AUR/MPR packages I'm maintaining.

I looked at the `PKGBUILD` script, though realistically I'd only be changing the `PKGBUILD` until upstream releases the next version of ElectronMail.

**Comment by ghost** [comment]
It would be nice to rename it too. "electron-mail-deb", the first dash is to be like upstream and the "-deb" is to show that it doesn't build anything.

One of the objectives is also to stay compatible with mpr helpers, haven't tested this, so it might need a bit more massaging.

**Comment by taivlam** [comment]
By MPR helper, I infer you basically mean [Mist](https://docs.makedeb.org/using-the-mpr/mist-the-mpr-cli/), correct?

I tried looking for MPR helpers, but the latest discussion around "MPR helper" was from around late 2022, such as this Linuxiac [article](https://linuxiac.com/mist-mpr-helper-for-debian-and-ubuntu/) on Mist.  Other than the content for the `makedeb` doc page on Mist, there's nothing else that matches the description - other than this March 2022 [snapshot](https://web.archive.org/web/20220324121421/https://docs.makedeb.org/mpr/list-of-mpr-helpers/) of MPR helpers in `makedeb`'s docs.

**Comment by ghost** [comment]
there's mist and una. I suspect they are ported versions  from aur helpers. Both are neglected. I'm not using any helper.

**Comment by taivlam** [comment]
Since ElectronMail hasn't pushed an update since October 2023, I'll wait until I officially create `electronmail-deb` for the next release before closing this issue (unless there is something stopping the upcoming `electronmail-deb` package).

Unrelated: I used your `-deb` package approach for Ente Auth as `ente-auth-deb` on the MPR, and it worked well.  So, I have credited you accordingly and I'll merge the outdated and nonworking `ente-auth-bin` that I previously created.

(For some reason, I mistakenly remembered that this was about Bitwarden and not ElectronMail; but this was cleared up when I reread this thread.  I'm not sure how this false memory/[Mandela effect](https://en.wikipedia.org/wiki/False_memory#Mandela_effect) came about.)

**Comment by ghost** [comment]
with a dash `electron-mail`, how upstream names the file.

**Comment by taivlam** [comment]
Currently only NixOS has used the base package name of `electron-mail` on [Repology](https://repology.org/project/electron-mail/versions) (for both [24.05](https://github.com/NixOS/nixpkgs/blob/release-24.05/pkgs/applications/networking/mailreaders/electron-mail/default.nix) and [Unstable](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/mailreaders/electron-mail/default.nix)).

However, checking the latest GH [release](https://github.com/vladimiry/electronmail/releases/latest) for ElectronMail shows that every binary name begins with `electron-mail*`.

I'll locally test `electron-mail-deb` for the MPR soon and make sure it's working before filing a merge request on the MPR.

**Comment by taivlam** [comment]
Have you used [Pacstall](https://pacstall.dev/)?  I discovered it yesterday.  Its [packages](https://pacstall.dev/packages) use the `-deb` convention for install scripts using plain DEB archives.

**Comment by ghost** [comment]
I knew about it but never used it, it's yet an other solution that deduplicates the package manager. meh...

**Comment by taivlam** [comment]
I spoke to Hunter Wittenborn on the MPR channel on Matrix, and he decided it was better to leave the `-bin`  named packages rather than to make package names that end with `-deb`.  (Those messages were around July 7th.)

So, due to that, I had to merge `ente-auth-deb` into `ente-auth-bin` (which didn't really work out the way I initially believed it would, but I fixed the situation); and `ente-auth-bin` had to stay.

However, I just need to test & verify that the simpler PKGBUILD method work, and then I can close this issue for ElectronMail.  I plan to increment the `pkgrel` number, since this update is for the `PKGBUILD` and ElectronMail hasn't made a "real" update.

**Comment by ghost** [comment]
~~you have the wrong file name in noextract~~

also isn't better to rename it electron-mail-bin? (with a dash)

**Comment by ghost** [comment]
Actually you forgot to rename the file as you download it to the expected name.

**Comment by ghost** [comment]
@taivlam
You missed this message. The filename in noextract is wrong.

**Comment by taivlam** [comment]
@pirate486743186 One last comment: I decided to keep `electronmail-bin` due to these reasons:
* Earlier this year, I submitted `ente-auth-bin`, but then tried to change it to `ente-auth-deb` by making a second new package.  Long story short, I changed it back to `ente-auth-bin` after discussing with @hwittenborn on the MPR Matrix channel.  The merge back to `etne-auth-bin` did not behave the way I expected it to (i.e., the comment history didn't actually merge; instead, the old comment set overwrote the new comment set), and I had to manually add the updates back to `ente-auth-bin`.
    * So, this explains why I'm not exploring the `-deb` suffix.
* Although I'm aware that in the GH release assets the base form of `electron-mail` is used, I think it makes sense to keep the base form of `electronmail`, as it is based on the human-writable spelling of ElectronMail.
    * This is based on my MPR submission of the desktop client of Standard Notes.  On GH, the GH organization name is `standardnotes` (even though the user/org name `standard-notes` doesn't seem to be taken) and its GH release asset name is `standard-notes`.  However, in writing we use "Standard Notes", so `standard-notes-bin` works for me as the MPR package name.
* Lastly, I asked Hunter directly about this on Matrix, but I didn't get a response - so, I'm going to take that as an implicit sign that he didn't want to rename this package from `electronmail-bin` to `electron-mail-bin`.

I was able to use the more minimal `PKGBUILD` structure you suggested and replaced my GH no-reply e-mail address with a SimpleLogin alias; so, I still think the MPR package has improved a lot from your feedback.

**Comment by ghost** [comment]
1. i got a bit confused earlier, one error is that you don't rename the file you download to the expected file name. The point of this, is to maintain compatibility with helpers.

like this, check for errors, didn't test it
`source=("${pkgname}_${pkgver}-${pkgrel}_${arch}.deb::downloadurl")`

2. because of the filename missmatch, noextract doesn't work and the deb gets extracted in src/
also in noextract you currently have _pkgrel instead of pkgrel

3.check that src/ remains empty and the file has the name a helper expects. If you ever change the name, check for these errors. Just wait for the next release to push small fixes like this.

4.hunter seams bussy latelly.

**Comment by taivlam** [comment]
I fixed the error, and also tested the package to make sure it's working.  (I haven't been good with testing every update.)

Also this reminded me that I made the same error in the `bitwarden-bin` package.
